import type { EducationPageConfig } from './types'

export const activeStatusOptions = [
  { label: '启用', value: 'active' },
  { label: '停用', value: 'inactive' },
]

export const studentStatusOptions = [
  { label: '在读', value: 'active' },
  { label: '待开课', value: 'pending' },
  { label: '停课', value: 'paused' },
  { label: '结课', value: 'finished' },
]

export const classStatusOptions = [
  { label: '筹备中', value: 'planning' },
  { label: '开班中', value: 'active' },
  { label: '已结班', value: 'finished' },
  { label: '已取消', value: 'cancelled' },
]

export const lessonStatusOptions = [
  { label: '待上课', value: 'scheduled' },
  { label: '已上课', value: 'completed' },
  { label: '已取消', value: 'cancelled' },
]

export const settlementStatusOptions = [
  { label: '待结算', value: 'pending' },
  { label: '已确认', value: 'confirmed' },
  { label: '已发放', value: 'paid' },
]

export const educationPageConfigs = {
  students: {
    domain: 'students',
    title: '学员管理',
    documentTitle: '学员管理',
    emptyText: '暂无学员',
    primaryField: 'student_name',
    searchPlaceholder: '搜索学员/家长/手机号',
    createText: '新增学员',
    exportText: '导出学员',
    statusOptions: studentStatusOptions,
    fields: [
      { key: 'student_name', title: '学员姓名', width: 140, primary: true, required: true },
      { key: 'parent_name', title: '家长姓名', width: 120, required: true },
      { key: 'parent_phone', title: '联系电话', width: 140, required: true },
      { key: 'grade', title: '年级', width: 100 },
      { key: 'campus_name', title: '所属校区', width: 140 },
      { key: 'status', title: '状态', width: 100, kind: 'select', options: studentStatusOptions },
      { key: 'created_at', title: '创建时间', width: 170, kind: 'date', datetime: true, hiddenInForm: true },
      { key: 'remark', title: '备注', width: 220, kind: 'textarea', hiddenInTable: true },
    ],
  },
  parents: {
    domain: 'parents',
    title: '家长管理',
    documentTitle: '家长管理',
    emptyText: '暂无家长',
    primaryField: 'parent_name',
    searchPlaceholder: '搜索家长/手机号/微信',
    createText: '新增家长',
    statusOptions: activeStatusOptions,
    fields: [
      { key: 'parent_name', title: '家长姓名', width: 140, primary: true, required: true },
      { key: 'phone', title: '手机号', width: 140, required: true },
      { key: 'wechat', title: '微信号', width: 140 },
      { key: 'student_name', title: '关联学员', width: 140 },
      { key: 'relationship', title: '关系', width: 100 },
      { key: 'status', title: '状态', width: 100, kind: 'select', options: activeStatusOptions },
      { key: 'remark', title: '备注', width: 220, kind: 'textarea', hiddenInTable: true },
    ],
  },
  teachers: {
    domain: 'teachers',
    title: '教师管理',
    documentTitle: '教师管理',
    emptyText: '暂无教师',
    primaryField: 'teacher_name',
    searchPlaceholder: '搜索教师/科目/手机号',
    createText: '新增教师',
    exportText: '导出教师',
    statusOptions: activeStatusOptions,
    fields: [
      { key: 'teacher_name', title: '教师姓名', width: 140, primary: true, required: true },
      { key: 'phone', title: '手机号', width: 140 },
      { key: 'subject', title: '授课科目', width: 130, required: true },
      { key: 'campus_name', title: '所属校区', width: 140 },
      { key: 'hourly_rate', title: '课时费', width: 120, kind: 'number', money: true },
      { key: 'status', title: '状态', width: 100, kind: 'select', options: activeStatusOptions },
      { key: 'remark', title: '备注', width: 220, kind: 'textarea', hiddenInTable: true },
    ],
  },
  courseProducts: {
    domain: 'course-products',
    title: '课程产品',
    documentTitle: '课程产品',
    emptyText: '暂无课程产品',
    primaryField: 'course_name',
    searchPlaceholder: '搜索课程/科目',
    createText: '新增课程产品',
    statusOptions: activeStatusOptions,
    fields: [
      { key: 'course_name', title: '课程名称', width: 180, primary: true, required: true },
      { key: 'subject', title: '科目', width: 120 },
      { key: 'course_type', title: '课程类型', width: 120 },
      { key: 'default_hours', title: '默认课时', width: 110, kind: 'number' },
      { key: 'list_price', title: '标价', width: 130, kind: 'number', money: true },
      { key: 'status', title: '状态', width: 100, kind: 'select', options: activeStatusOptions },
      { key: 'description', title: '课程说明', width: 240, kind: 'textarea', hiddenInTable: true },
    ],
  },
  packages: {
    domain: 'packages',
    title: '课程套餐',
    documentTitle: '课程套餐',
    emptyText: '暂无套餐',
    primaryField: 'package_name',
    searchPlaceholder: '搜索套餐/课程',
    createText: '新增套餐',
    statusOptions: activeStatusOptions,
    fields: [
      { key: 'package_name', title: '套餐名称', width: 180, primary: true, required: true },
      { key: 'course_name', title: '课程产品', width: 160 },
      { key: 'hours', title: '课时数', width: 100, kind: 'number', required: true },
      { key: 'price', title: '套餐价格', width: 130, kind: 'number', money: true },
      { key: 'valid_days', title: '有效期天数', width: 120, kind: 'number' },
      { key: 'status', title: '状态', width: 100, kind: 'select', options: activeStatusOptions },
      { key: 'description', title: '套餐说明', width: 240, kind: 'textarea', hiddenInTable: true },
    ],
  },
  classes: {
    domain: 'classes',
    title: '班级管理',
    documentTitle: '班级管理',
    emptyText: '暂无班级',
    primaryField: 'class_name',
    searchPlaceholder: '搜索班级/教师/课程',
    createText: '新增班级',
    statusOptions: classStatusOptions,
    fields: [
      { key: 'class_name', title: '班级名称', width: 180, primary: true, required: true },
      { key: 'course_name', title: '课程', width: 150 },
      { key: 'teacher_name', title: '任课教师', width: 130 },
      { key: 'campus_name', title: '校区', width: 130 },
      { key: 'capacity', title: '容量', width: 90, kind: 'number' },
      { key: 'student_count', title: '学员数', width: 100, kind: 'number', hiddenInForm: true },
      { key: 'status', title: '状态', width: 100, kind: 'select', options: classStatusOptions },
      { key: 'start_date', title: '开班日期', width: 130, kind: 'date' },
    ],
  },
  lessons: {
    domain: 'lessons',
    title: '课次管理',
    documentTitle: '课次管理',
    emptyText: '暂无课次',
    primaryField: 'lesson_title',
    searchPlaceholder: '搜索课次/班级/教师',
    createText: '新增课次',
    statusOptions: lessonStatusOptions,
    fields: [
      { key: 'lesson_title', title: '课次主题', width: 180, primary: true, required: true },
      { key: 'class_name', title: '班级', width: 150 },
      { key: 'teacher_name', title: '教师', width: 130 },
      { key: 'lesson_at', title: '上课时间', width: 170, kind: 'date', datetime: true, required: true },
      { key: 'duration_minutes', title: '时长分钟', width: 110, kind: 'number' },
      { key: 'consumed_hours', title: '消课课时', width: 110, kind: 'number' },
      { key: 'status', title: '状态', width: 100, kind: 'select', options: lessonStatusOptions },
      { key: 'remark', title: '备注', width: 220, kind: 'textarea', hiddenInTable: true },
    ],
  },
  consumption: {
    domain: 'consumption',
    title: '消课记录',
    documentTitle: '消课记录',
    emptyText: '暂无消课记录',
    primaryField: 'student_name',
    searchPlaceholder: '搜索学员/课次/班级',
    createText: '登记消课',
    exportText: '导出消课',
    fields: [
      { key: 'student_name', title: '学员姓名', width: 140, primary: true, required: true },
      { key: 'lesson_title', title: '课次主题', width: 180 },
      { key: 'class_name', title: '班级', width: 140 },
      { key: 'consumed_hours', title: '消课课时', width: 110, kind: 'number', required: true },
      { key: 'consumed_at', title: '消课时间', width: 170, kind: 'date', datetime: true },
      { key: 'operator_name', title: '操作人', width: 120, hiddenInForm: true },
      { key: 'remark', title: '备注', width: 220, kind: 'textarea' },
    ],
  },
  balances: {
    domain: 'balances',
    title: '课时余额',
    documentTitle: '课时余额',
    emptyText: '暂无余额记录',
    primaryField: 'student_name',
    searchPlaceholder: '搜索学员/套餐',
    createText: '调整余额',
    exportText: '导出余额',
    fields: [
      { key: 'student_name', title: '学员姓名', width: 140, primary: true, required: true },
      { key: 'package_name', title: '套餐', width: 160 },
      { key: 'total_hours', title: '总课时', width: 100, kind: 'number' },
      { key: 'consumed_hours', title: '已消课时', width: 110, kind: 'number' },
      { key: 'remaining_hours', title: '剩余课时', width: 110, kind: 'number', required: true },
      { key: 'expires_at', title: '到期日', width: 130, kind: 'date' },
      { key: 'remark', title: '备注', width: 220, kind: 'textarea', hiddenInTable: true },
    ],
  },
  finance: {
    domain: 'finance',
    title: '教务财务',
    documentTitle: '教务财务',
    emptyText: '暂无财务记录',
    primaryField: 'transaction_no',
    searchPlaceholder: '搜索单号/学员/套餐',
    createText: '新增流水',
    exportText: '导出流水',
    fields: [
      { key: 'transaction_no', title: '流水号', width: 170, primary: true, required: true },
      { key: 'student_name', title: '学员', width: 130 },
      { key: 'business_type', title: '业务类型', width: 120 },
      { key: 'amount', title: '金额', width: 130, kind: 'number', money: true, required: true },
      { key: 'paid_at', title: '发生时间', width: 170, kind: 'date', datetime: true },
      { key: 'operator_name', title: '经办人', width: 120, hiddenInForm: true },
      { key: 'remark', title: '备注', width: 220, kind: 'textarea' },
    ],
  },
  teacherSettlements: {
    domain: 'teacher-settlements',
    title: '教师结算',
    documentTitle: '教师结算',
    emptyText: '暂无结算记录',
    primaryField: 'settlement_no',
    searchPlaceholder: '搜索结算单/教师',
    createText: '新增结算',
    exportText: '导出结算',
    statusOptions: settlementStatusOptions,
    fields: [
      { key: 'settlement_no', title: '结算单号', width: 170, primary: true, required: true },
      { key: 'teacher_name', title: '教师', width: 130, required: true },
      { key: 'period', title: '结算周期', width: 130 },
      { key: 'lesson_count', title: '课次数', width: 100, kind: 'number' },
      { key: 'total_hours', title: '结算课时', width: 110, kind: 'number' },
      { key: 'amount', title: '结算金额', width: 130, kind: 'number', money: true, required: true },
      { key: 'status', title: '状态', width: 100, kind: 'select', options: settlementStatusOptions },
      { key: 'remark', title: '备注', width: 220, kind: 'textarea', hiddenInTable: true },
    ],
  },
} satisfies Record<string, EducationPageConfig>
