/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadSubmitRouteImport } from './routes/lead-submit'
import { Route as DiscTestRouteImport } from './routes/disc-test'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as FullscreenRouteRouteImport } from './routes/_fullscreen/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as FullscreenExcelDemoRouteImport } from './routes/_fullscreen/excel-demo'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedYunkeRouteRouteImport } from './routes/_authenticated/yunke/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedHrRouteRouteImport } from './routes/_authenticated/hr/route'
import { Route as AuthenticatedCrmRouteRouteImport } from './routes/_authenticated/crm/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedYunkeIndexRouteImport } from './routes/_authenticated/yunke/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedYunkeLoginStatusRouteImport } from './routes/_authenticated/yunke/login-status'
import { Route as AuthenticatedYunkeDashboardRouteImport } from './routes/_authenticated/yunke/dashboard'
import { Route as AuthenticatedYunkeCredentialsRouteImport } from './routes/_authenticated/yunke/credentials'
import { Route as AuthenticatedYunkeCallRecordsRouteImport } from './routes/_authenticated/yunke/call-records'
import { Route as AuthenticatedYunkeAiAssistantRouteImport } from './routes/_authenticated/yunke/ai-assistant'
import { Route as AuthenticatedYunkeAdvisorTrainingRouteImport } from './routes/_authenticated/yunke/advisor-training'
import { Route as AuthenticatedYunkeAccountsRouteImport } from './routes/_authenticated/yunke/accounts'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedHrDiscTestRouteImport } from './routes/_authenticated/hr/disc-test'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDemoTdesignLeadsRouteImport } from './routes/_authenticated/demo/tdesign-leads'
import { Route as AuthenticatedCrmWorkbenchRouteImport } from './routes/_authenticated/crm/workbench'
import { Route as AuthenticatedCrmVisitScheduleRouteImport } from './routes/_authenticated/crm/visit-schedule'
import { Route as AuthenticatedCrmPendingApprovalsRouteImport } from './routes/_authenticated/crm/pending-approvals'
import { Route as AuthenticatedCrmOrdersRouteImport } from './routes/_authenticated/crm/orders'
import { Route as AuthenticatedCrmLeadConversionRouteImport } from './routes/_authenticated/crm/lead-conversion'
import { Route as AuthenticatedCrmContinuousCallRouteImport } from './routes/_authenticated/crm/continuous-call'
import { Route as AuthenticatedCrmCallRecordsRouteImport } from './routes/_authenticated/crm/call-records'
import { Route as AuthenticatedCrmBatchImportRouteImport } from './routes/_authenticated/crm/batch-import'
import { Route as AuthenticatedCrmAiAssistantRouteImport } from './routes/_authenticated/crm/ai-assistant'
import { Route as AuthenticatedAdminYunkeAccountsRouteImport } from './routes/_authenticated/admin/yunke-accounts'
import { Route as AuthenticatedAdminWebhookHooksRouteImport } from './routes/_authenticated/admin/webhook-hooks'
import { Route as AuthenticatedAdminSourceChannelsRouteImport } from './routes/_authenticated/admin/source-channels'
import { Route as AuthenticatedAdminSchoolsRouteImport } from './routes/_authenticated/admin/schools'
import { Route as AuthenticatedAdminScheduledTasksRouteImport } from './routes/_authenticated/admin/scheduled-tasks'
import { Route as AuthenticatedAdminRegionsRouteImport } from './routes/_authenticated/admin/regions'
import { Route as AuthenticatedAdminPositionsRouteImport } from './routes/_authenticated/admin/positions'
import { Route as AuthenticatedAdminPageAccessRouteImport } from './routes/_authenticated/admin/page-access'
import { Route as AuthenticatedAdminOrganizationTreeRouteImport } from './routes/_authenticated/admin/organization-tree'
import { Route as AuthenticatedAdminLeadAccessStatsRouteImport } from './routes/_authenticated/admin/lead-access-stats'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin/integrations'
import { Route as AuthenticatedAdminIdentitiesRouteImport } from './routes/_authenticated/admin/identities'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin/employees'
import { Route as AuthenticatedAdminEmployeeHierarchyRouteImport } from './routes/_authenticated/admin/employee-hierarchy'
import { Route as AuthenticatedAdminDistrictsRouteImport } from './routes/_authenticated/admin/districts'
import { Route as AuthenticatedAdminDingtalkRobotsRouteImport } from './routes/_authenticated/admin/dingtalk-robots'
import { Route as AuthenticatedAdminDepartmentsRouteImport } from './routes/_authenticated/admin/departments'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminDailyNoticesRouteImport } from './routes/_authenticated/admin/daily-notices'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin/courses'
import { Route as AuthenticatedAdminCampusesRouteImport } from './routes/_authenticated/admin/campuses'
import { Route as AuthenticatedAdminCampusDepartmentsRouteImport } from './routes/_authenticated/admin/campus-departments'
import { Route as AuthenticatedAdminCallConfigRouteImport } from './routes/_authenticated/admin/call-config'
import { Route as AuthenticatedAdminAsrConfigRouteImport } from './routes/_authenticated/admin/asr-config'
import { Route as AuthenticatedAdminAreasRouteImport } from './routes/_authenticated/admin/areas'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin/api-keys'
import { Route as AuthenticatedAdminAiConfigRouteImport } from './routes/_authenticated/admin/ai-config'
import { Route as AuthenticatedCrmLeadsIndexRouteImport } from './routes/_authenticated/crm/leads/index'
import { Route as AuthenticatedCrmLeadsPoolRouteImport } from './routes/_authenticated/crm/leads/pool'
import { Route as AuthenticatedCrmDataStatisticsMarketingRouteImport } from './routes/_authenticated/crm/data-statistics/marketing'
import { Route as AuthenticatedCrmDataStatisticsConsultingRouteImport } from './routes/_authenticated/crm/data-statistics/consulting'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadSubmitRoute = LeadSubmitRouteImport.update({
  id: '/lead-submit',
  path: '/lead-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscTestRoute = DiscTestRouteImport.update({
  id: '/disc-test',
  path: '/disc-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const FullscreenRouteRoute = FullscreenRouteRouteImport.update({
  id: '/_fullscreen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const FullscreenExcelDemoRoute = FullscreenExcelDemoRouteImport.update({
  id: '/excel-demo',
  path: '/excel-demo',
  getParentRoute: () => FullscreenRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedYunkeRouteRoute = AuthenticatedYunkeRouteRouteImport.update({
  id: '/yunke',
  path: '/yunke',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrRouteRoute = AuthenticatedHrRouteRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRouteRoute = AuthenticatedCrmRouteRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedYunkeIndexRoute = AuthenticatedYunkeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedYunkeRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRouteRoute,
} as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedYunkeLoginStatusRoute =
  AuthenticatedYunkeLoginStatusRouteImport.update({
    id: '/login-status',
    path: '/login-status',
    getParentRoute: () => AuthenticatedYunkeRouteRoute,
  } as any)
const AuthenticatedYunkeDashboardRoute =
  AuthenticatedYunkeDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedYunkeRouteRoute,
  } as any)
const AuthenticatedYunkeCredentialsRoute =
  AuthenticatedYunkeCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AuthenticatedYunkeRouteRoute,
  } as any)
const AuthenticatedYunkeCallRecordsRoute =
  AuthenticatedYunkeCallRecordsRouteImport.update({
    id: '/call-records',
    path: '/call-records',
    getParentRoute: () => AuthenticatedYunkeRouteRoute,
  } as any)
const AuthenticatedYunkeAiAssistantRoute =
  AuthenticatedYunkeAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedYunkeRouteRoute,
  } as any)
const AuthenticatedYunkeAdvisorTrainingRoute =
  AuthenticatedYunkeAdvisorTrainingRouteImport.update({
    id: '/advisor-training',
    path: '/advisor-training',
    getParentRoute: () => AuthenticatedYunkeRouteRoute,
  } as any)
const AuthenticatedYunkeAccountsRoute =
  AuthenticatedYunkeAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedYunkeRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHrDiscTestRoute = AuthenticatedHrDiscTestRouteImport.update({
  id: '/disc-test',
  path: '/disc-test',
  getParentRoute: () => AuthenticatedHrRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoTdesignLeadsRoute =
  AuthenticatedDemoTdesignLeadsRouteImport.update({
    id: '/demo/tdesign-leads',
    path: '/demo/tdesign-leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmWorkbenchRoute =
  AuthenticatedCrmWorkbenchRouteImport.update({
    id: '/workbench',
    path: '/workbench',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmVisitScheduleRoute =
  AuthenticatedCrmVisitScheduleRouteImport.update({
    id: '/visit-schedule',
    path: '/visit-schedule',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmPendingApprovalsRoute =
  AuthenticatedCrmPendingApprovalsRouteImport.update({
    id: '/pending-approvals',
    path: '/pending-approvals',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmOrdersRoute = AuthenticatedCrmOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedCrmRouteRoute,
} as any)
const AuthenticatedCrmLeadConversionRoute =
  AuthenticatedCrmLeadConversionRouteImport.update({
    id: '/lead-conversion',
    path: '/lead-conversion',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmContinuousCallRoute =
  AuthenticatedCrmContinuousCallRouteImport.update({
    id: '/continuous-call',
    path: '/continuous-call',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmCallRecordsRoute =
  AuthenticatedCrmCallRecordsRouteImport.update({
    id: '/call-records',
    path: '/call-records',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmBatchImportRoute =
  AuthenticatedCrmBatchImportRouteImport.update({
    id: '/batch-import',
    path: '/batch-import',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmAiAssistantRoute =
  AuthenticatedCrmAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedAdminYunkeAccountsRoute =
  AuthenticatedAdminYunkeAccountsRouteImport.update({
    id: '/yunke-accounts',
    path: '/yunke-accounts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminWebhookHooksRoute =
  AuthenticatedAdminWebhookHooksRouteImport.update({
    id: '/webhook-hooks',
    path: '/webhook-hooks',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSourceChannelsRoute =
  AuthenticatedAdminSourceChannelsRouteImport.update({
    id: '/source-channels',
    path: '/source-channels',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSchoolsRoute =
  AuthenticatedAdminSchoolsRouteImport.update({
    id: '/schools',
    path: '/schools',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminScheduledTasksRoute =
  AuthenticatedAdminScheduledTasksRouteImport.update({
    id: '/scheduled-tasks',
    path: '/scheduled-tasks',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRegionsRoute =
  AuthenticatedAdminRegionsRouteImport.update({
    id: '/regions',
    path: '/regions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPositionsRoute =
  AuthenticatedAdminPositionsRouteImport.update({
    id: '/positions',
    path: '/positions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPageAccessRoute =
  AuthenticatedAdminPageAccessRouteImport.update({
    id: '/page-access',
    path: '/page-access',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrganizationTreeRoute =
  AuthenticatedAdminOrganizationTreeRouteImport.update({
    id: '/organization-tree',
    path: '/organization-tree',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLeadAccessStatsRoute =
  AuthenticatedAdminLeadAccessStatsRouteImport.update({
    id: '/lead-access-stats',
    path: '/lead-access-stats',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIdentitiesRoute =
  AuthenticatedAdminIdentitiesRouteImport.update({
    id: '/identities',
    path: '/identities',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmployeeHierarchyRoute =
  AuthenticatedAdminEmployeeHierarchyRouteImport.update({
    id: '/employee-hierarchy',
    path: '/employee-hierarchy',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDistrictsRoute =
  AuthenticatedAdminDistrictsRouteImport.update({
    id: '/districts',
    path: '/districts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDingtalkRobotsRoute =
  AuthenticatedAdminDingtalkRobotsRouteImport.update({
    id: '/dingtalk-robots',
    path: '/dingtalk-robots',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDepartmentsRoute =
  AuthenticatedAdminDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDailyNoticesRoute =
  AuthenticatedAdminDailyNoticesRouteImport.update({
    id: '/daily-notices',
    path: '/daily-notices',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCampusesRoute =
  AuthenticatedAdminCampusesRouteImport.update({
    id: '/campuses',
    path: '/campuses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCampusDepartmentsRoute =
  AuthenticatedAdminCampusDepartmentsRouteImport.update({
    id: '/campus-departments',
    path: '/campus-departments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCallConfigRoute =
  AuthenticatedAdminCallConfigRouteImport.update({
    id: '/call-config',
    path: '/call-config',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAsrConfigRoute =
  AuthenticatedAdminAsrConfigRouteImport.update({
    id: '/asr-config',
    path: '/asr-config',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAreasRoute = AuthenticatedAdminAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAiConfigRoute =
  AuthenticatedAdminAiConfigRouteImport.update({
    id: '/ai-config',
    path: '/ai-config',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedCrmLeadsIndexRoute =
  AuthenticatedCrmLeadsIndexRouteImport.update({
    id: '/leads/',
    path: '/leads/',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmLeadsPoolRoute =
  AuthenticatedCrmLeadsPoolRouteImport.update({
    id: '/leads/pool',
    path: '/leads/pool',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmDataStatisticsMarketingRoute =
  AuthenticatedCrmDataStatisticsMarketingRouteImport.update({
    id: '/data-statistics/marketing',
    path: '/data-statistics/marketing',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmDataStatisticsConsultingRoute =
  AuthenticatedCrmDataStatisticsConsultingRouteImport.update({
    id: '/data-statistics/consulting',
    path: '/data-statistics/consulting',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/disc-test': typeof DiscTestRoute
  '/lead-submit': typeof LeadSubmitRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/crm': typeof AuthenticatedCrmRouteRouteWithChildren
  '/hr': typeof AuthenticatedHrRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/yunke': typeof AuthenticatedYunkeRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/excel-demo': typeof FullscreenExcelDemoRoute
  '/admin/ai-config': typeof AuthenticatedAdminAiConfigRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/admin/asr-config': typeof AuthenticatedAdminAsrConfigRoute
  '/admin/call-config': typeof AuthenticatedAdminCallConfigRoute
  '/admin/campus-departments': typeof AuthenticatedAdminCampusDepartmentsRoute
  '/admin/campuses': typeof AuthenticatedAdminCampusesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/daily-notices': typeof AuthenticatedAdminDailyNoticesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/dingtalk-robots': typeof AuthenticatedAdminDingtalkRobotsRoute
  '/admin/districts': typeof AuthenticatedAdminDistrictsRoute
  '/admin/employee-hierarchy': typeof AuthenticatedAdminEmployeeHierarchyRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/identities': typeof AuthenticatedAdminIdentitiesRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/lead-access-stats': typeof AuthenticatedAdminLeadAccessStatsRoute
  '/admin/organization-tree': typeof AuthenticatedAdminOrganizationTreeRoute
  '/admin/page-access': typeof AuthenticatedAdminPageAccessRoute
  '/admin/positions': typeof AuthenticatedAdminPositionsRoute
  '/admin/regions': typeof AuthenticatedAdminRegionsRoute
  '/admin/scheduled-tasks': typeof AuthenticatedAdminScheduledTasksRoute
  '/admin/schools': typeof AuthenticatedAdminSchoolsRoute
  '/admin/source-channels': typeof AuthenticatedAdminSourceChannelsRoute
  '/admin/webhook-hooks': typeof AuthenticatedAdminWebhookHooksRoute
  '/admin/yunke-accounts': typeof AuthenticatedAdminYunkeAccountsRoute
  '/crm/ai-assistant': typeof AuthenticatedCrmAiAssistantRoute
  '/crm/batch-import': typeof AuthenticatedCrmBatchImportRoute
  '/crm/call-records': typeof AuthenticatedCrmCallRecordsRoute
  '/crm/continuous-call': typeof AuthenticatedCrmContinuousCallRoute
  '/crm/lead-conversion': typeof AuthenticatedCrmLeadConversionRoute
  '/crm/orders': typeof AuthenticatedCrmOrdersRoute
  '/crm/pending-approvals': typeof AuthenticatedCrmPendingApprovalsRoute
  '/crm/visit-schedule': typeof AuthenticatedCrmVisitScheduleRoute
  '/crm/workbench': typeof AuthenticatedCrmWorkbenchRoute
  '/demo/tdesign-leads': typeof AuthenticatedDemoTdesignLeadsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/hr/disc-test': typeof AuthenticatedHrDiscTestRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/yunke/accounts': typeof AuthenticatedYunkeAccountsRoute
  '/yunke/advisor-training': typeof AuthenticatedYunkeAdvisorTrainingRoute
  '/yunke/ai-assistant': typeof AuthenticatedYunkeAiAssistantRoute
  '/yunke/call-records': typeof AuthenticatedYunkeCallRecordsRoute
  '/yunke/credentials': typeof AuthenticatedYunkeCredentialsRoute
  '/yunke/dashboard': typeof AuthenticatedYunkeDashboardRoute
  '/yunke/login-status': typeof AuthenticatedYunkeLoginStatusRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/yunke/': typeof AuthenticatedYunkeIndexRoute
  '/crm/data-statistics/consulting': typeof AuthenticatedCrmDataStatisticsConsultingRoute
  '/crm/data-statistics/marketing': typeof AuthenticatedCrmDataStatisticsMarketingRoute
  '/crm/leads/pool': typeof AuthenticatedCrmLeadsPoolRoute
  '/crm/leads/': typeof AuthenticatedCrmLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/disc-test': typeof DiscTestRoute
  '/lead-submit': typeof LeadSubmitRoute
  '/login': typeof LoginRoute
  '/hr': typeof AuthenticatedHrRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/excel-demo': typeof FullscreenExcelDemoRoute
  '/admin/ai-config': typeof AuthenticatedAdminAiConfigRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/admin/asr-config': typeof AuthenticatedAdminAsrConfigRoute
  '/admin/call-config': typeof AuthenticatedAdminCallConfigRoute
  '/admin/campus-departments': typeof AuthenticatedAdminCampusDepartmentsRoute
  '/admin/campuses': typeof AuthenticatedAdminCampusesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/daily-notices': typeof AuthenticatedAdminDailyNoticesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/dingtalk-robots': typeof AuthenticatedAdminDingtalkRobotsRoute
  '/admin/districts': typeof AuthenticatedAdminDistrictsRoute
  '/admin/employee-hierarchy': typeof AuthenticatedAdminEmployeeHierarchyRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/identities': typeof AuthenticatedAdminIdentitiesRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/lead-access-stats': typeof AuthenticatedAdminLeadAccessStatsRoute
  '/admin/organization-tree': typeof AuthenticatedAdminOrganizationTreeRoute
  '/admin/page-access': typeof AuthenticatedAdminPageAccessRoute
  '/admin/positions': typeof AuthenticatedAdminPositionsRoute
  '/admin/regions': typeof AuthenticatedAdminRegionsRoute
  '/admin/scheduled-tasks': typeof AuthenticatedAdminScheduledTasksRoute
  '/admin/schools': typeof AuthenticatedAdminSchoolsRoute
  '/admin/source-channels': typeof AuthenticatedAdminSourceChannelsRoute
  '/admin/webhook-hooks': typeof AuthenticatedAdminWebhookHooksRoute
  '/admin/yunke-accounts': typeof AuthenticatedAdminYunkeAccountsRoute
  '/crm/ai-assistant': typeof AuthenticatedCrmAiAssistantRoute
  '/crm/batch-import': typeof AuthenticatedCrmBatchImportRoute
  '/crm/call-records': typeof AuthenticatedCrmCallRecordsRoute
  '/crm/continuous-call': typeof AuthenticatedCrmContinuousCallRoute
  '/crm/lead-conversion': typeof AuthenticatedCrmLeadConversionRoute
  '/crm/orders': typeof AuthenticatedCrmOrdersRoute
  '/crm/pending-approvals': typeof AuthenticatedCrmPendingApprovalsRoute
  '/crm/visit-schedule': typeof AuthenticatedCrmVisitScheduleRoute
  '/crm/workbench': typeof AuthenticatedCrmWorkbenchRoute
  '/demo/tdesign-leads': typeof AuthenticatedDemoTdesignLeadsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/hr/disc-test': typeof AuthenticatedHrDiscTestRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/yunke/accounts': typeof AuthenticatedYunkeAccountsRoute
  '/yunke/advisor-training': typeof AuthenticatedYunkeAdvisorTrainingRoute
  '/yunke/ai-assistant': typeof AuthenticatedYunkeAiAssistantRoute
  '/yunke/call-records': typeof AuthenticatedYunkeCallRecordsRoute
  '/yunke/credentials': typeof AuthenticatedYunkeCredentialsRoute
  '/yunke/dashboard': typeof AuthenticatedYunkeDashboardRoute
  '/yunke/login-status': typeof AuthenticatedYunkeLoginStatusRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/yunke': typeof AuthenticatedYunkeIndexRoute
  '/crm/data-statistics/consulting': typeof AuthenticatedCrmDataStatisticsConsultingRoute
  '/crm/data-statistics/marketing': typeof AuthenticatedCrmDataStatisticsMarketingRoute
  '/crm/leads/pool': typeof AuthenticatedCrmLeadsPoolRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_fullscreen': typeof FullscreenRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/disc-test': typeof DiscTestRoute
  '/lead-submit': typeof LeadSubmitRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/crm': typeof AuthenticatedCrmRouteRouteWithChildren
  '/_authenticated/hr': typeof AuthenticatedHrRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/yunke': typeof AuthenticatedYunkeRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_fullscreen/excel-demo': typeof FullscreenExcelDemoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/ai-config': typeof AuthenticatedAdminAiConfigRoute
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/_authenticated/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/_authenticated/admin/asr-config': typeof AuthenticatedAdminAsrConfigRoute
  '/_authenticated/admin/call-config': typeof AuthenticatedAdminCallConfigRoute
  '/_authenticated/admin/campus-departments': typeof AuthenticatedAdminCampusDepartmentsRoute
  '/_authenticated/admin/campuses': typeof AuthenticatedAdminCampusesRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/daily-notices': typeof AuthenticatedAdminDailyNoticesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/_authenticated/admin/dingtalk-robots': typeof AuthenticatedAdminDingtalkRobotsRoute
  '/_authenticated/admin/districts': typeof AuthenticatedAdminDistrictsRoute
  '/_authenticated/admin/employee-hierarchy': typeof AuthenticatedAdminEmployeeHierarchyRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/identities': typeof AuthenticatedAdminIdentitiesRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/lead-access-stats': typeof AuthenticatedAdminLeadAccessStatsRoute
  '/_authenticated/admin/organization-tree': typeof AuthenticatedAdminOrganizationTreeRoute
  '/_authenticated/admin/page-access': typeof AuthenticatedAdminPageAccessRoute
  '/_authenticated/admin/positions': typeof AuthenticatedAdminPositionsRoute
  '/_authenticated/admin/regions': typeof AuthenticatedAdminRegionsRoute
  '/_authenticated/admin/scheduled-tasks': typeof AuthenticatedAdminScheduledTasksRoute
  '/_authenticated/admin/schools': typeof AuthenticatedAdminSchoolsRoute
  '/_authenticated/admin/source-channels': typeof AuthenticatedAdminSourceChannelsRoute
  '/_authenticated/admin/webhook-hooks': typeof AuthenticatedAdminWebhookHooksRoute
  '/_authenticated/admin/yunke-accounts': typeof AuthenticatedAdminYunkeAccountsRoute
  '/_authenticated/crm/ai-assistant': typeof AuthenticatedCrmAiAssistantRoute
  '/_authenticated/crm/batch-import': typeof AuthenticatedCrmBatchImportRoute
  '/_authenticated/crm/call-records': typeof AuthenticatedCrmCallRecordsRoute
  '/_authenticated/crm/continuous-call': typeof AuthenticatedCrmContinuousCallRoute
  '/_authenticated/crm/lead-conversion': typeof AuthenticatedCrmLeadConversionRoute
  '/_authenticated/crm/orders': typeof AuthenticatedCrmOrdersRoute
  '/_authenticated/crm/pending-approvals': typeof AuthenticatedCrmPendingApprovalsRoute
  '/_authenticated/crm/visit-schedule': typeof AuthenticatedCrmVisitScheduleRoute
  '/_authenticated/crm/workbench': typeof AuthenticatedCrmWorkbenchRoute
  '/_authenticated/demo/tdesign-leads': typeof AuthenticatedDemoTdesignLeadsRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/hr/disc-test': typeof AuthenticatedHrDiscTestRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/yunke/accounts': typeof AuthenticatedYunkeAccountsRoute
  '/_authenticated/yunke/advisor-training': typeof AuthenticatedYunkeAdvisorTrainingRoute
  '/_authenticated/yunke/ai-assistant': typeof AuthenticatedYunkeAiAssistantRoute
  '/_authenticated/yunke/call-records': typeof AuthenticatedYunkeCallRecordsRoute
  '/_authenticated/yunke/credentials': typeof AuthenticatedYunkeCredentialsRoute
  '/_authenticated/yunke/dashboard': typeof AuthenticatedYunkeDashboardRoute
  '/_authenticated/yunke/login-status': typeof AuthenticatedYunkeLoginStatusRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/yunke/': typeof AuthenticatedYunkeIndexRoute
  '/_authenticated/crm/data-statistics/consulting': typeof AuthenticatedCrmDataStatisticsConsultingRoute
  '/_authenticated/crm/data-statistics/marketing': typeof AuthenticatedCrmDataStatisticsMarketingRoute
  '/_authenticated/crm/leads/pool': typeof AuthenticatedCrmLeadsPoolRoute
  '/_authenticated/crm/leads/': typeof AuthenticatedCrmLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/disc-test'
    | '/lead-submit'
    | '/login'
    | '/admin'
    | '/crm'
    | '/hr'
    | '/settings'
    | '/yunke'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/excel-demo'
    | '/admin/ai-config'
    | '/admin/api-keys'
    | '/admin/areas'
    | '/admin/asr-config'
    | '/admin/call-config'
    | '/admin/campus-departments'
    | '/admin/campuses'
    | '/admin/courses'
    | '/admin/daily-notices'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/dingtalk-robots'
    | '/admin/districts'
    | '/admin/employee-hierarchy'
    | '/admin/employees'
    | '/admin/identities'
    | '/admin/integrations'
    | '/admin/lead-access-stats'
    | '/admin/organization-tree'
    | '/admin/page-access'
    | '/admin/positions'
    | '/admin/regions'
    | '/admin/scheduled-tasks'
    | '/admin/schools'
    | '/admin/source-channels'
    | '/admin/webhook-hooks'
    | '/admin/yunke-accounts'
    | '/crm/ai-assistant'
    | '/crm/batch-import'
    | '/crm/call-records'
    | '/crm/continuous-call'
    | '/crm/lead-conversion'
    | '/crm/orders'
    | '/crm/pending-approvals'
    | '/crm/visit-schedule'
    | '/crm/workbench'
    | '/demo/tdesign-leads'
    | '/errors/$error'
    | '/hr/disc-test'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/yunke/accounts'
    | '/yunke/advisor-training'
    | '/yunke/ai-assistant'
    | '/yunke/call-records'
    | '/yunke/credentials'
    | '/yunke/dashboard'
    | '/yunke/login-status'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/admin/'
    | '/apps/'
    | '/chats/'
    | '/crm/'
    | '/help-center/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
    | '/yunke/'
    | '/crm/data-statistics/consulting'
    | '/crm/data-statistics/marketing'
    | '/crm/leads/pool'
    | '/crm/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clerk'
    | '/disc-test'
    | '/lead-submit'
    | '/login'
    | '/hr'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/excel-demo'
    | '/admin/ai-config'
    | '/admin/api-keys'
    | '/admin/areas'
    | '/admin/asr-config'
    | '/admin/call-config'
    | '/admin/campus-departments'
    | '/admin/campuses'
    | '/admin/courses'
    | '/admin/daily-notices'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/dingtalk-robots'
    | '/admin/districts'
    | '/admin/employee-hierarchy'
    | '/admin/employees'
    | '/admin/identities'
    | '/admin/integrations'
    | '/admin/lead-access-stats'
    | '/admin/organization-tree'
    | '/admin/page-access'
    | '/admin/positions'
    | '/admin/regions'
    | '/admin/scheduled-tasks'
    | '/admin/schools'
    | '/admin/source-channels'
    | '/admin/webhook-hooks'
    | '/admin/yunke-accounts'
    | '/crm/ai-assistant'
    | '/crm/batch-import'
    | '/crm/call-records'
    | '/crm/continuous-call'
    | '/crm/lead-conversion'
    | '/crm/orders'
    | '/crm/pending-approvals'
    | '/crm/visit-schedule'
    | '/crm/workbench'
    | '/demo/tdesign-leads'
    | '/errors/$error'
    | '/hr/disc-test'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/yunke/accounts'
    | '/yunke/advisor-training'
    | '/yunke/ai-assistant'
    | '/yunke/call-records'
    | '/yunke/credentials'
    | '/yunke/dashboard'
    | '/yunke/login-status'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/admin'
    | '/apps'
    | '/chats'
    | '/crm'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/yunke'
    | '/crm/data-statistics/consulting'
    | '/crm/data-statistics/marketing'
    | '/crm/leads/pool'
    | '/crm/leads'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_fullscreen'
    | '/clerk'
    | '/disc-test'
    | '/lead-submit'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/crm'
    | '/_authenticated/hr'
    | '/_authenticated/settings'
    | '/_authenticated/yunke'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_fullscreen/excel-demo'
    | '/_authenticated/'
    | '/_authenticated/admin/ai-config'
    | '/_authenticated/admin/api-keys'
    | '/_authenticated/admin/areas'
    | '/_authenticated/admin/asr-config'
    | '/_authenticated/admin/call-config'
    | '/_authenticated/admin/campus-departments'
    | '/_authenticated/admin/campuses'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/daily-notices'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/departments'
    | '/_authenticated/admin/dingtalk-robots'
    | '/_authenticated/admin/districts'
    | '/_authenticated/admin/employee-hierarchy'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/identities'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/lead-access-stats'
    | '/_authenticated/admin/organization-tree'
    | '/_authenticated/admin/page-access'
    | '/_authenticated/admin/positions'
    | '/_authenticated/admin/regions'
    | '/_authenticated/admin/scheduled-tasks'
    | '/_authenticated/admin/schools'
    | '/_authenticated/admin/source-channels'
    | '/_authenticated/admin/webhook-hooks'
    | '/_authenticated/admin/yunke-accounts'
    | '/_authenticated/crm/ai-assistant'
    | '/_authenticated/crm/batch-import'
    | '/_authenticated/crm/call-records'
    | '/_authenticated/crm/continuous-call'
    | '/_authenticated/crm/lead-conversion'
    | '/_authenticated/crm/orders'
    | '/_authenticated/crm/pending-approvals'
    | '/_authenticated/crm/visit-schedule'
    | '/_authenticated/crm/workbench'
    | '/_authenticated/demo/tdesign-leads'
    | '/_authenticated/errors/$error'
    | '/_authenticated/hr/disc-test'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/yunke/accounts'
    | '/_authenticated/yunke/advisor-training'
    | '/_authenticated/yunke/ai-assistant'
    | '/_authenticated/yunke/call-records'
    | '/_authenticated/yunke/credentials'
    | '/_authenticated/yunke/dashboard'
    | '/_authenticated/yunke/login-status'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/admin/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/crm/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/yunke/'
    | '/_authenticated/crm/data-statistics/consulting'
    | '/_authenticated/crm/data-statistics/marketing'
    | '/_authenticated/crm/leads/pool'
    | '/_authenticated/crm/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  FullscreenRouteRoute: typeof FullscreenRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  DiscTestRoute: typeof DiscTestRoute
  LeadSubmitRoute: typeof LeadSubmitRoute
  LoginRoute: typeof LoginRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-submit': {
      id: '/lead-submit'
      path: '/lead-submit'
      fullPath: '/lead-submit'
      preLoaderRoute: typeof LeadSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disc-test': {
      id: '/disc-test'
      path: '/disc-test'
      fullPath: '/disc-test'
      preLoaderRoute: typeof DiscTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_fullscreen': {
      id: '/_fullscreen'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FullscreenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_fullscreen/excel-demo': {
      id: '/_fullscreen/excel-demo'
      path: '/excel-demo'
      fullPath: '/excel-demo'
      preLoaderRoute: typeof FullscreenExcelDemoRouteImport
      parentRoute: typeof FullscreenRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/yunke': {
      id: '/_authenticated/yunke'
      path: '/yunke'
      fullPath: '/yunke'
      preLoaderRoute: typeof AuthenticatedYunkeRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yunke/': {
      id: '/_authenticated/yunke/'
      path: '/'
      fullPath: '/yunke/'
      preLoaderRoute: typeof AuthenticatedYunkeIndexRouteImport
      parentRoute: typeof AuthenticatedYunkeRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/yunke/login-status': {
      id: '/_authenticated/yunke/login-status'
      path: '/login-status'
      fullPath: '/yunke/login-status'
      preLoaderRoute: typeof AuthenticatedYunkeLoginStatusRouteImport
      parentRoute: typeof AuthenticatedYunkeRouteRoute
    }
    '/_authenticated/yunke/dashboard': {
      id: '/_authenticated/yunke/dashboard'
      path: '/dashboard'
      fullPath: '/yunke/dashboard'
      preLoaderRoute: typeof AuthenticatedYunkeDashboardRouteImport
      parentRoute: typeof AuthenticatedYunkeRouteRoute
    }
    '/_authenticated/yunke/credentials': {
      id: '/_authenticated/yunke/credentials'
      path: '/credentials'
      fullPath: '/yunke/credentials'
      preLoaderRoute: typeof AuthenticatedYunkeCredentialsRouteImport
      parentRoute: typeof AuthenticatedYunkeRouteRoute
    }
    '/_authenticated/yunke/call-records': {
      id: '/_authenticated/yunke/call-records'
      path: '/call-records'
      fullPath: '/yunke/call-records'
      preLoaderRoute: typeof AuthenticatedYunkeCallRecordsRouteImport
      parentRoute: typeof AuthenticatedYunkeRouteRoute
    }
    '/_authenticated/yunke/ai-assistant': {
      id: '/_authenticated/yunke/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/yunke/ai-assistant'
      preLoaderRoute: typeof AuthenticatedYunkeAiAssistantRouteImport
      parentRoute: typeof AuthenticatedYunkeRouteRoute
    }
    '/_authenticated/yunke/advisor-training': {
      id: '/_authenticated/yunke/advisor-training'
      path: '/advisor-training'
      fullPath: '/yunke/advisor-training'
      preLoaderRoute: typeof AuthenticatedYunkeAdvisorTrainingRouteImport
      parentRoute: typeof AuthenticatedYunkeRouteRoute
    }
    '/_authenticated/yunke/accounts': {
      id: '/_authenticated/yunke/accounts'
      path: '/accounts'
      fullPath: '/yunke/accounts'
      preLoaderRoute: typeof AuthenticatedYunkeAccountsRouteImport
      parentRoute: typeof AuthenticatedYunkeRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/hr/disc-test': {
      id: '/_authenticated/hr/disc-test'
      path: '/disc-test'
      fullPath: '/hr/disc-test'
      preLoaderRoute: typeof AuthenticatedHrDiscTestRouteImport
      parentRoute: typeof AuthenticatedHrRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/tdesign-leads': {
      id: '/_authenticated/demo/tdesign-leads'
      path: '/demo/tdesign-leads'
      fullPath: '/demo/tdesign-leads'
      preLoaderRoute: typeof AuthenticatedDemoTdesignLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/workbench': {
      id: '/_authenticated/crm/workbench'
      path: '/workbench'
      fullPath: '/crm/workbench'
      preLoaderRoute: typeof AuthenticatedCrmWorkbenchRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/visit-schedule': {
      id: '/_authenticated/crm/visit-schedule'
      path: '/visit-schedule'
      fullPath: '/crm/visit-schedule'
      preLoaderRoute: typeof AuthenticatedCrmVisitScheduleRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/pending-approvals': {
      id: '/_authenticated/crm/pending-approvals'
      path: '/pending-approvals'
      fullPath: '/crm/pending-approvals'
      preLoaderRoute: typeof AuthenticatedCrmPendingApprovalsRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/orders': {
      id: '/_authenticated/crm/orders'
      path: '/orders'
      fullPath: '/crm/orders'
      preLoaderRoute: typeof AuthenticatedCrmOrdersRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/lead-conversion': {
      id: '/_authenticated/crm/lead-conversion'
      path: '/lead-conversion'
      fullPath: '/crm/lead-conversion'
      preLoaderRoute: typeof AuthenticatedCrmLeadConversionRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/continuous-call': {
      id: '/_authenticated/crm/continuous-call'
      path: '/continuous-call'
      fullPath: '/crm/continuous-call'
      preLoaderRoute: typeof AuthenticatedCrmContinuousCallRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/call-records': {
      id: '/_authenticated/crm/call-records'
      path: '/call-records'
      fullPath: '/crm/call-records'
      preLoaderRoute: typeof AuthenticatedCrmCallRecordsRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/batch-import': {
      id: '/_authenticated/crm/batch-import'
      path: '/batch-import'
      fullPath: '/crm/batch-import'
      preLoaderRoute: typeof AuthenticatedCrmBatchImportRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/ai-assistant': {
      id: '/_authenticated/crm/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/crm/ai-assistant'
      preLoaderRoute: typeof AuthenticatedCrmAiAssistantRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/admin/yunke-accounts': {
      id: '/_authenticated/admin/yunke-accounts'
      path: '/yunke-accounts'
      fullPath: '/admin/yunke-accounts'
      preLoaderRoute: typeof AuthenticatedAdminYunkeAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/webhook-hooks': {
      id: '/_authenticated/admin/webhook-hooks'
      path: '/webhook-hooks'
      fullPath: '/admin/webhook-hooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhookHooksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/source-channels': {
      id: '/_authenticated/admin/source-channels'
      path: '/source-channels'
      fullPath: '/admin/source-channels'
      preLoaderRoute: typeof AuthenticatedAdminSourceChannelsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/schools': {
      id: '/_authenticated/admin/schools'
      path: '/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AuthenticatedAdminSchoolsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/scheduled-tasks': {
      id: '/_authenticated/admin/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/admin/scheduled-tasks'
      preLoaderRoute: typeof AuthenticatedAdminScheduledTasksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/regions': {
      id: '/_authenticated/admin/regions'
      path: '/regions'
      fullPath: '/admin/regions'
      preLoaderRoute: typeof AuthenticatedAdminRegionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/positions': {
      id: '/_authenticated/admin/positions'
      path: '/positions'
      fullPath: '/admin/positions'
      preLoaderRoute: typeof AuthenticatedAdminPositionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/page-access': {
      id: '/_authenticated/admin/page-access'
      path: '/page-access'
      fullPath: '/admin/page-access'
      preLoaderRoute: typeof AuthenticatedAdminPageAccessRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/organization-tree': {
      id: '/_authenticated/admin/organization-tree'
      path: '/organization-tree'
      fullPath: '/admin/organization-tree'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationTreeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lead-access-stats': {
      id: '/_authenticated/admin/lead-access-stats'
      path: '/lead-access-stats'
      fullPath: '/admin/lead-access-stats'
      preLoaderRoute: typeof AuthenticatedAdminLeadAccessStatsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/identities': {
      id: '/_authenticated/admin/identities'
      path: '/identities'
      fullPath: '/admin/identities'
      preLoaderRoute: typeof AuthenticatedAdminIdentitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/employee-hierarchy': {
      id: '/_authenticated/admin/employee-hierarchy'
      path: '/employee-hierarchy'
      fullPath: '/admin/employee-hierarchy'
      preLoaderRoute: typeof AuthenticatedAdminEmployeeHierarchyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/districts': {
      id: '/_authenticated/admin/districts'
      path: '/districts'
      fullPath: '/admin/districts'
      preLoaderRoute: typeof AuthenticatedAdminDistrictsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dingtalk-robots': {
      id: '/_authenticated/admin/dingtalk-robots'
      path: '/dingtalk-robots'
      fullPath: '/admin/dingtalk-robots'
      preLoaderRoute: typeof AuthenticatedAdminDingtalkRobotsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/departments': {
      id: '/_authenticated/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AuthenticatedAdminDepartmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/daily-notices': {
      id: '/_authenticated/admin/daily-notices'
      path: '/daily-notices'
      fullPath: '/admin/daily-notices'
      preLoaderRoute: typeof AuthenticatedAdminDailyNoticesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/campuses': {
      id: '/_authenticated/admin/campuses'
      path: '/campuses'
      fullPath: '/admin/campuses'
      preLoaderRoute: typeof AuthenticatedAdminCampusesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/campus-departments': {
      id: '/_authenticated/admin/campus-departments'
      path: '/campus-departments'
      fullPath: '/admin/campus-departments'
      preLoaderRoute: typeof AuthenticatedAdminCampusDepartmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/call-config': {
      id: '/_authenticated/admin/call-config'
      path: '/call-config'
      fullPath: '/admin/call-config'
      preLoaderRoute: typeof AuthenticatedAdminCallConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/asr-config': {
      id: '/_authenticated/admin/asr-config'
      path: '/asr-config'
      fullPath: '/admin/asr-config'
      preLoaderRoute: typeof AuthenticatedAdminAsrConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/areas': {
      id: '/_authenticated/admin/areas'
      path: '/areas'
      fullPath: '/admin/areas'
      preLoaderRoute: typeof AuthenticatedAdminAreasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ai-config': {
      id: '/_authenticated/admin/ai-config'
      path: '/ai-config'
      fullPath: '/admin/ai-config'
      preLoaderRoute: typeof AuthenticatedAdminAiConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/crm/leads/': {
      id: '/_authenticated/crm/leads/'
      path: '/leads'
      fullPath: '/crm/leads/'
      preLoaderRoute: typeof AuthenticatedCrmLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/leads/pool': {
      id: '/_authenticated/crm/leads/pool'
      path: '/leads/pool'
      fullPath: '/crm/leads/pool'
      preLoaderRoute: typeof AuthenticatedCrmLeadsPoolRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/data-statistics/marketing': {
      id: '/_authenticated/crm/data-statistics/marketing'
      path: '/data-statistics/marketing'
      fullPath: '/crm/data-statistics/marketing'
      preLoaderRoute: typeof AuthenticatedCrmDataStatisticsMarketingRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/data-statistics/consulting': {
      id: '/_authenticated/crm/data-statistics/consulting'
      path: '/data-statistics/consulting'
      fullPath: '/crm/data-statistics/consulting'
      preLoaderRoute: typeof AuthenticatedCrmDataStatisticsConsultingRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAiConfigRoute: typeof AuthenticatedAdminAiConfigRoute
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
  AuthenticatedAdminAreasRoute: typeof AuthenticatedAdminAreasRoute
  AuthenticatedAdminAsrConfigRoute: typeof AuthenticatedAdminAsrConfigRoute
  AuthenticatedAdminCallConfigRoute: typeof AuthenticatedAdminCallConfigRoute
  AuthenticatedAdminCampusDepartmentsRoute: typeof AuthenticatedAdminCampusDepartmentsRoute
  AuthenticatedAdminCampusesRoute: typeof AuthenticatedAdminCampusesRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminDailyNoticesRoute: typeof AuthenticatedAdminDailyNoticesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDepartmentsRoute: typeof AuthenticatedAdminDepartmentsRoute
  AuthenticatedAdminDingtalkRobotsRoute: typeof AuthenticatedAdminDingtalkRobotsRoute
  AuthenticatedAdminDistrictsRoute: typeof AuthenticatedAdminDistrictsRoute
  AuthenticatedAdminEmployeeHierarchyRoute: typeof AuthenticatedAdminEmployeeHierarchyRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminIdentitiesRoute: typeof AuthenticatedAdminIdentitiesRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminLeadAccessStatsRoute: typeof AuthenticatedAdminLeadAccessStatsRoute
  AuthenticatedAdminOrganizationTreeRoute: typeof AuthenticatedAdminOrganizationTreeRoute
  AuthenticatedAdminPageAccessRoute: typeof AuthenticatedAdminPageAccessRoute
  AuthenticatedAdminPositionsRoute: typeof AuthenticatedAdminPositionsRoute
  AuthenticatedAdminRegionsRoute: typeof AuthenticatedAdminRegionsRoute
  AuthenticatedAdminScheduledTasksRoute: typeof AuthenticatedAdminScheduledTasksRoute
  AuthenticatedAdminSchoolsRoute: typeof AuthenticatedAdminSchoolsRoute
  AuthenticatedAdminSourceChannelsRoute: typeof AuthenticatedAdminSourceChannelsRoute
  AuthenticatedAdminWebhookHooksRoute: typeof AuthenticatedAdminWebhookHooksRoute
  AuthenticatedAdminYunkeAccountsRoute: typeof AuthenticatedAdminYunkeAccountsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAiConfigRoute: AuthenticatedAdminAiConfigRoute,
    AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
    AuthenticatedAdminAreasRoute: AuthenticatedAdminAreasRoute,
    AuthenticatedAdminAsrConfigRoute: AuthenticatedAdminAsrConfigRoute,
    AuthenticatedAdminCallConfigRoute: AuthenticatedAdminCallConfigRoute,
    AuthenticatedAdminCampusDepartmentsRoute:
      AuthenticatedAdminCampusDepartmentsRoute,
    AuthenticatedAdminCampusesRoute: AuthenticatedAdminCampusesRoute,
    AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
    AuthenticatedAdminDailyNoticesRoute: AuthenticatedAdminDailyNoticesRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminDepartmentsRoute: AuthenticatedAdminDepartmentsRoute,
    AuthenticatedAdminDingtalkRobotsRoute:
      AuthenticatedAdminDingtalkRobotsRoute,
    AuthenticatedAdminDistrictsRoute: AuthenticatedAdminDistrictsRoute,
    AuthenticatedAdminEmployeeHierarchyRoute:
      AuthenticatedAdminEmployeeHierarchyRoute,
    AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
    AuthenticatedAdminIdentitiesRoute: AuthenticatedAdminIdentitiesRoute,
    AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
    AuthenticatedAdminLeadAccessStatsRoute:
      AuthenticatedAdminLeadAccessStatsRoute,
    AuthenticatedAdminOrganizationTreeRoute:
      AuthenticatedAdminOrganizationTreeRoute,
    AuthenticatedAdminPageAccessRoute: AuthenticatedAdminPageAccessRoute,
    AuthenticatedAdminPositionsRoute: AuthenticatedAdminPositionsRoute,
    AuthenticatedAdminRegionsRoute: AuthenticatedAdminRegionsRoute,
    AuthenticatedAdminScheduledTasksRoute:
      AuthenticatedAdminScheduledTasksRoute,
    AuthenticatedAdminSchoolsRoute: AuthenticatedAdminSchoolsRoute,
    AuthenticatedAdminSourceChannelsRoute:
      AuthenticatedAdminSourceChannelsRoute,
    AuthenticatedAdminWebhookHooksRoute: AuthenticatedAdminWebhookHooksRoute,
    AuthenticatedAdminYunkeAccountsRoute: AuthenticatedAdminYunkeAccountsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedCrmRouteRouteChildren {
  AuthenticatedCrmAiAssistantRoute: typeof AuthenticatedCrmAiAssistantRoute
  AuthenticatedCrmBatchImportRoute: typeof AuthenticatedCrmBatchImportRoute
  AuthenticatedCrmCallRecordsRoute: typeof AuthenticatedCrmCallRecordsRoute
  AuthenticatedCrmContinuousCallRoute: typeof AuthenticatedCrmContinuousCallRoute
  AuthenticatedCrmLeadConversionRoute: typeof AuthenticatedCrmLeadConversionRoute
  AuthenticatedCrmOrdersRoute: typeof AuthenticatedCrmOrdersRoute
  AuthenticatedCrmPendingApprovalsRoute: typeof AuthenticatedCrmPendingApprovalsRoute
  AuthenticatedCrmVisitScheduleRoute: typeof AuthenticatedCrmVisitScheduleRoute
  AuthenticatedCrmWorkbenchRoute: typeof AuthenticatedCrmWorkbenchRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
  AuthenticatedCrmDataStatisticsConsultingRoute: typeof AuthenticatedCrmDataStatisticsConsultingRoute
  AuthenticatedCrmDataStatisticsMarketingRoute: typeof AuthenticatedCrmDataStatisticsMarketingRoute
  AuthenticatedCrmLeadsPoolRoute: typeof AuthenticatedCrmLeadsPoolRoute
  AuthenticatedCrmLeadsIndexRoute: typeof AuthenticatedCrmLeadsIndexRoute
}

const AuthenticatedCrmRouteRouteChildren: AuthenticatedCrmRouteRouteChildren = {
  AuthenticatedCrmAiAssistantRoute: AuthenticatedCrmAiAssistantRoute,
  AuthenticatedCrmBatchImportRoute: AuthenticatedCrmBatchImportRoute,
  AuthenticatedCrmCallRecordsRoute: AuthenticatedCrmCallRecordsRoute,
  AuthenticatedCrmContinuousCallRoute: AuthenticatedCrmContinuousCallRoute,
  AuthenticatedCrmLeadConversionRoute: AuthenticatedCrmLeadConversionRoute,
  AuthenticatedCrmOrdersRoute: AuthenticatedCrmOrdersRoute,
  AuthenticatedCrmPendingApprovalsRoute: AuthenticatedCrmPendingApprovalsRoute,
  AuthenticatedCrmVisitScheduleRoute: AuthenticatedCrmVisitScheduleRoute,
  AuthenticatedCrmWorkbenchRoute: AuthenticatedCrmWorkbenchRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
  AuthenticatedCrmDataStatisticsConsultingRoute:
    AuthenticatedCrmDataStatisticsConsultingRoute,
  AuthenticatedCrmDataStatisticsMarketingRoute:
    AuthenticatedCrmDataStatisticsMarketingRoute,
  AuthenticatedCrmLeadsPoolRoute: AuthenticatedCrmLeadsPoolRoute,
  AuthenticatedCrmLeadsIndexRoute: AuthenticatedCrmLeadsIndexRoute,
}

const AuthenticatedCrmRouteRouteWithChildren =
  AuthenticatedCrmRouteRoute._addFileChildren(
    AuthenticatedCrmRouteRouteChildren,
  )

interface AuthenticatedHrRouteRouteChildren {
  AuthenticatedHrDiscTestRoute: typeof AuthenticatedHrDiscTestRoute
}

const AuthenticatedHrRouteRouteChildren: AuthenticatedHrRouteRouteChildren = {
  AuthenticatedHrDiscTestRoute: AuthenticatedHrDiscTestRoute,
}

const AuthenticatedHrRouteRouteWithChildren =
  AuthenticatedHrRouteRoute._addFileChildren(AuthenticatedHrRouteRouteChildren)

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedYunkeRouteRouteChildren {
  AuthenticatedYunkeAccountsRoute: typeof AuthenticatedYunkeAccountsRoute
  AuthenticatedYunkeAdvisorTrainingRoute: typeof AuthenticatedYunkeAdvisorTrainingRoute
  AuthenticatedYunkeAiAssistantRoute: typeof AuthenticatedYunkeAiAssistantRoute
  AuthenticatedYunkeCallRecordsRoute: typeof AuthenticatedYunkeCallRecordsRoute
  AuthenticatedYunkeCredentialsRoute: typeof AuthenticatedYunkeCredentialsRoute
  AuthenticatedYunkeDashboardRoute: typeof AuthenticatedYunkeDashboardRoute
  AuthenticatedYunkeLoginStatusRoute: typeof AuthenticatedYunkeLoginStatusRoute
  AuthenticatedYunkeIndexRoute: typeof AuthenticatedYunkeIndexRoute
}

const AuthenticatedYunkeRouteRouteChildren: AuthenticatedYunkeRouteRouteChildren =
  {
    AuthenticatedYunkeAccountsRoute: AuthenticatedYunkeAccountsRoute,
    AuthenticatedYunkeAdvisorTrainingRoute:
      AuthenticatedYunkeAdvisorTrainingRoute,
    AuthenticatedYunkeAiAssistantRoute: AuthenticatedYunkeAiAssistantRoute,
    AuthenticatedYunkeCallRecordsRoute: AuthenticatedYunkeCallRecordsRoute,
    AuthenticatedYunkeCredentialsRoute: AuthenticatedYunkeCredentialsRoute,
    AuthenticatedYunkeDashboardRoute: AuthenticatedYunkeDashboardRoute,
    AuthenticatedYunkeLoginStatusRoute: AuthenticatedYunkeLoginStatusRoute,
    AuthenticatedYunkeIndexRoute: AuthenticatedYunkeIndexRoute,
  }

const AuthenticatedYunkeRouteRouteWithChildren =
  AuthenticatedYunkeRouteRoute._addFileChildren(
    AuthenticatedYunkeRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCrmRouteRoute: typeof AuthenticatedCrmRouteRouteWithChildren
  AuthenticatedHrRouteRoute: typeof AuthenticatedHrRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedYunkeRouteRoute: typeof AuthenticatedYunkeRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDemoTdesignLeadsRoute: typeof AuthenticatedDemoTdesignLeadsRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCrmRouteRoute: AuthenticatedCrmRouteRouteWithChildren,
  AuthenticatedHrRouteRoute: AuthenticatedHrRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedYunkeRouteRoute: AuthenticatedYunkeRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDemoTdesignLeadsRoute: AuthenticatedDemoTdesignLeadsRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface FullscreenRouteRouteChildren {
  FullscreenExcelDemoRoute: typeof FullscreenExcelDemoRoute
}

const FullscreenRouteRouteChildren: FullscreenRouteRouteChildren = {
  FullscreenExcelDemoRoute: FullscreenExcelDemoRoute,
}

const FullscreenRouteRouteWithChildren = FullscreenRouteRoute._addFileChildren(
  FullscreenRouteRouteChildren,
)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  FullscreenRouteRoute: FullscreenRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  DiscTestRoute: DiscTestRoute,
  LeadSubmitRoute: LeadSubmitRoute,
  LoginRoute: LoginRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
