/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCrmWorkbenchRouteImport } from './routes/_authenticated/crm/workbench'
import { Route as AuthenticatedCrmOrdersRouteImport } from './routes/_authenticated/crm/orders'
import { Route as AuthenticatedCrmLeadConversionRouteImport } from './routes/_authenticated/crm/lead-conversion'
import { Route as AuthenticatedCrmContinuousCallRouteImport } from './routes/_authenticated/crm/continuous-call'
import { Route as AuthenticatedCrmBatchImportRouteImport } from './routes/_authenticated/crm/batch-import'
import { Route as AuthenticatedAdminYunkeAccountsRouteImport } from './routes/_authenticated/admin/yunke-accounts'
import { Route as AuthenticatedAdminWebhookHooksRouteImport } from './routes/_authenticated/admin/webhook-hooks'
import { Route as AuthenticatedAdminTempDiscRecordsRouteImport } from './routes/_authenticated/admin/temp-disc-records'
import { Route as AuthenticatedAdminSourceChannelsRouteImport } from './routes/_authenticated/admin/source-channels'
import { Route as AuthenticatedAdminSchoolsRouteImport } from './routes/_authenticated/admin/schools'
import { Route as AuthenticatedAdminRegionsRouteImport } from './routes/_authenticated/admin/regions'
import { Route as AuthenticatedAdminPositionsRouteImport } from './routes/_authenticated/admin/positions'
import { Route as AuthenticatedAdminOrganizationTreeRouteImport } from './routes/_authenticated/admin/organization-tree'
import { Route as AuthenticatedAdminLeadAccessStatsRouteImport } from './routes/_authenticated/admin/lead-access-stats'
import { Route as AuthenticatedAdminIdentitiesRouteImport } from './routes/_authenticated/admin/identities'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin/employees'
import { Route as AuthenticatedAdminEmployeeHierarchyRouteImport } from './routes/_authenticated/admin/employee-hierarchy'
import { Route as AuthenticatedAdminDistrictsRouteImport } from './routes/_authenticated/admin/districts'
import { Route as AuthenticatedAdminDiscTestRouteImport } from './routes/_authenticated/admin/disc-test'
import { Route as AuthenticatedAdminDingtalkRobotsRouteImport } from './routes/_authenticated/admin/dingtalk-robots'
import { Route as AuthenticatedAdminDepartmentsRouteImport } from './routes/_authenticated/admin/departments'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin/courses'
import { Route as AuthenticatedAdminCampusesRouteImport } from './routes/_authenticated/admin/campuses'
import { Route as AuthenticatedAdminCampusDepartmentsRouteImport } from './routes/_authenticated/admin/campus-departments'
import { Route as AuthenticatedAdminCallConfigRouteImport } from './routes/_authenticated/admin/call-config'
import { Route as AuthenticatedAdminAreasRouteImport } from './routes/_authenticated/admin/areas'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin/api-keys'
import { Route as AuthenticatedCrmLeadsIndexRouteImport } from './routes/_authenticated/crm/leads/index'
import { Route as AuthenticatedCrmLeadsPoolRouteImport } from './routes/_authenticated/crm/leads/pool'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmWorkbenchRoute =
  AuthenticatedCrmWorkbenchRouteImport.update({
    id: '/crm/workbench',
    path: '/crm/workbench',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmOrdersRoute = AuthenticatedCrmOrdersRouteImport.update({
  id: '/crm/orders',
  path: '/crm/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmLeadConversionRoute =
  AuthenticatedCrmLeadConversionRouteImport.update({
    id: '/crm/lead-conversion',
    path: '/crm/lead-conversion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmContinuousCallRoute =
  AuthenticatedCrmContinuousCallRouteImport.update({
    id: '/crm/continuous-call',
    path: '/crm/continuous-call',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmBatchImportRoute =
  AuthenticatedCrmBatchImportRouteImport.update({
    id: '/crm/batch-import',
    path: '/crm/batch-import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminYunkeAccountsRoute =
  AuthenticatedAdminYunkeAccountsRouteImport.update({
    id: '/admin/yunke-accounts',
    path: '/admin/yunke-accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminWebhookHooksRoute =
  AuthenticatedAdminWebhookHooksRouteImport.update({
    id: '/admin/webhook-hooks',
    path: '/admin/webhook-hooks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTempDiscRecordsRoute =
  AuthenticatedAdminTempDiscRecordsRouteImport.update({
    id: '/admin/temp-disc-records',
    path: '/admin/temp-disc-records',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSourceChannelsRoute =
  AuthenticatedAdminSourceChannelsRouteImport.update({
    id: '/admin/source-channels',
    path: '/admin/source-channels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSchoolsRoute =
  AuthenticatedAdminSchoolsRouteImport.update({
    id: '/admin/schools',
    path: '/admin/schools',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRegionsRoute =
  AuthenticatedAdminRegionsRouteImport.update({
    id: '/admin/regions',
    path: '/admin/regions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPositionsRoute =
  AuthenticatedAdminPositionsRouteImport.update({
    id: '/admin/positions',
    path: '/admin/positions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrganizationTreeRoute =
  AuthenticatedAdminOrganizationTreeRouteImport.update({
    id: '/admin/organization-tree',
    path: '/admin/organization-tree',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLeadAccessStatsRoute =
  AuthenticatedAdminLeadAccessStatsRouteImport.update({
    id: '/admin/lead-access-stats',
    path: '/admin/lead-access-stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIdentitiesRoute =
  AuthenticatedAdminIdentitiesRouteImport.update({
    id: '/admin/identities',
    path: '/admin/identities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/admin/employees',
    path: '/admin/employees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmployeeHierarchyRoute =
  AuthenticatedAdminEmployeeHierarchyRouteImport.update({
    id: '/admin/employee-hierarchy',
    path: '/admin/employee-hierarchy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDistrictsRoute =
  AuthenticatedAdminDistrictsRouteImport.update({
    id: '/admin/districts',
    path: '/admin/districts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDiscTestRoute =
  AuthenticatedAdminDiscTestRouteImport.update({
    id: '/admin/disc-test',
    path: '/admin/disc-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDingtalkRobotsRoute =
  AuthenticatedAdminDingtalkRobotsRouteImport.update({
    id: '/admin/dingtalk-robots',
    path: '/admin/dingtalk-robots',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDepartmentsRoute =
  AuthenticatedAdminDepartmentsRouteImport.update({
    id: '/admin/departments',
    path: '/admin/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/admin/courses',
    path: '/admin/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCampusesRoute =
  AuthenticatedAdminCampusesRouteImport.update({
    id: '/admin/campuses',
    path: '/admin/campuses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCampusDepartmentsRoute =
  AuthenticatedAdminCampusDepartmentsRouteImport.update({
    id: '/admin/campus-departments',
    path: '/admin/campus-departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCallConfigRoute =
  AuthenticatedAdminCallConfigRouteImport.update({
    id: '/admin/call-config',
    path: '/admin/call-config',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAreasRoute = AuthenticatedAdminAreasRouteImport.update({
  id: '/admin/areas',
  path: '/admin/areas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/admin/api-keys',
    path: '/admin/api-keys',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmLeadsIndexRoute =
  AuthenticatedCrmLeadsIndexRouteImport.update({
    id: '/crm/leads/',
    path: '/crm/leads/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmLeadsPoolRoute =
  AuthenticatedCrmLeadsPoolRouteImport.update({
    id: '/crm/leads/pool',
    path: '/crm/leads/pool',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/admin/call-config': typeof AuthenticatedAdminCallConfigRoute
  '/admin/campus-departments': typeof AuthenticatedAdminCampusDepartmentsRoute
  '/admin/campuses': typeof AuthenticatedAdminCampusesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/dingtalk-robots': typeof AuthenticatedAdminDingtalkRobotsRoute
  '/admin/disc-test': typeof AuthenticatedAdminDiscTestRoute
  '/admin/districts': typeof AuthenticatedAdminDistrictsRoute
  '/admin/employee-hierarchy': typeof AuthenticatedAdminEmployeeHierarchyRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/identities': typeof AuthenticatedAdminIdentitiesRoute
  '/admin/lead-access-stats': typeof AuthenticatedAdminLeadAccessStatsRoute
  '/admin/organization-tree': typeof AuthenticatedAdminOrganizationTreeRoute
  '/admin/positions': typeof AuthenticatedAdminPositionsRoute
  '/admin/regions': typeof AuthenticatedAdminRegionsRoute
  '/admin/schools': typeof AuthenticatedAdminSchoolsRoute
  '/admin/source-channels': typeof AuthenticatedAdminSourceChannelsRoute
  '/admin/temp-disc-records': typeof AuthenticatedAdminTempDiscRecordsRoute
  '/admin/webhook-hooks': typeof AuthenticatedAdminWebhookHooksRoute
  '/admin/yunke-accounts': typeof AuthenticatedAdminYunkeAccountsRoute
  '/crm/batch-import': typeof AuthenticatedCrmBatchImportRoute
  '/crm/continuous-call': typeof AuthenticatedCrmContinuousCallRoute
  '/crm/lead-conversion': typeof AuthenticatedCrmLeadConversionRoute
  '/crm/orders': typeof AuthenticatedCrmOrdersRoute
  '/crm/workbench': typeof AuthenticatedCrmWorkbenchRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/crm/leads/pool': typeof AuthenticatedCrmLeadsPoolRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/admin/call-config': typeof AuthenticatedAdminCallConfigRoute
  '/admin/campus-departments': typeof AuthenticatedAdminCampusDepartmentsRoute
  '/admin/campuses': typeof AuthenticatedAdminCampusesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/dingtalk-robots': typeof AuthenticatedAdminDingtalkRobotsRoute
  '/admin/disc-test': typeof AuthenticatedAdminDiscTestRoute
  '/admin/districts': typeof AuthenticatedAdminDistrictsRoute
  '/admin/employee-hierarchy': typeof AuthenticatedAdminEmployeeHierarchyRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/identities': typeof AuthenticatedAdminIdentitiesRoute
  '/admin/lead-access-stats': typeof AuthenticatedAdminLeadAccessStatsRoute
  '/admin/organization-tree': typeof AuthenticatedAdminOrganizationTreeRoute
  '/admin/positions': typeof AuthenticatedAdminPositionsRoute
  '/admin/regions': typeof AuthenticatedAdminRegionsRoute
  '/admin/schools': typeof AuthenticatedAdminSchoolsRoute
  '/admin/source-channels': typeof AuthenticatedAdminSourceChannelsRoute
  '/admin/temp-disc-records': typeof AuthenticatedAdminTempDiscRecordsRoute
  '/admin/webhook-hooks': typeof AuthenticatedAdminWebhookHooksRoute
  '/admin/yunke-accounts': typeof AuthenticatedAdminYunkeAccountsRoute
  '/crm/batch-import': typeof AuthenticatedCrmBatchImportRoute
  '/crm/continuous-call': typeof AuthenticatedCrmContinuousCallRoute
  '/crm/lead-conversion': typeof AuthenticatedCrmLeadConversionRoute
  '/crm/orders': typeof AuthenticatedCrmOrdersRoute
  '/crm/workbench': typeof AuthenticatedCrmWorkbenchRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/crm/leads/pool': typeof AuthenticatedCrmLeadsPoolRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/_authenticated/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/_authenticated/admin/call-config': typeof AuthenticatedAdminCallConfigRoute
  '/_authenticated/admin/campus-departments': typeof AuthenticatedAdminCampusDepartmentsRoute
  '/_authenticated/admin/campuses': typeof AuthenticatedAdminCampusesRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/_authenticated/admin/dingtalk-robots': typeof AuthenticatedAdminDingtalkRobotsRoute
  '/_authenticated/admin/disc-test': typeof AuthenticatedAdminDiscTestRoute
  '/_authenticated/admin/districts': typeof AuthenticatedAdminDistrictsRoute
  '/_authenticated/admin/employee-hierarchy': typeof AuthenticatedAdminEmployeeHierarchyRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/identities': typeof AuthenticatedAdminIdentitiesRoute
  '/_authenticated/admin/lead-access-stats': typeof AuthenticatedAdminLeadAccessStatsRoute
  '/_authenticated/admin/organization-tree': typeof AuthenticatedAdminOrganizationTreeRoute
  '/_authenticated/admin/positions': typeof AuthenticatedAdminPositionsRoute
  '/_authenticated/admin/regions': typeof AuthenticatedAdminRegionsRoute
  '/_authenticated/admin/schools': typeof AuthenticatedAdminSchoolsRoute
  '/_authenticated/admin/source-channels': typeof AuthenticatedAdminSourceChannelsRoute
  '/_authenticated/admin/temp-disc-records': typeof AuthenticatedAdminTempDiscRecordsRoute
  '/_authenticated/admin/webhook-hooks': typeof AuthenticatedAdminWebhookHooksRoute
  '/_authenticated/admin/yunke-accounts': typeof AuthenticatedAdminYunkeAccountsRoute
  '/_authenticated/crm/batch-import': typeof AuthenticatedCrmBatchImportRoute
  '/_authenticated/crm/continuous-call': typeof AuthenticatedCrmContinuousCallRoute
  '/_authenticated/crm/lead-conversion': typeof AuthenticatedCrmLeadConversionRoute
  '/_authenticated/crm/orders': typeof AuthenticatedCrmOrdersRoute
  '/_authenticated/crm/workbench': typeof AuthenticatedCrmWorkbenchRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/crm/leads/pool': typeof AuthenticatedCrmLeadsPoolRoute
  '/_authenticated/crm/leads/': typeof AuthenticatedCrmLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/login'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/admin/api-keys'
    | '/admin/areas'
    | '/admin/call-config'
    | '/admin/campus-departments'
    | '/admin/campuses'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/dingtalk-robots'
    | '/admin/disc-test'
    | '/admin/districts'
    | '/admin/employee-hierarchy'
    | '/admin/employees'
    | '/admin/identities'
    | '/admin/lead-access-stats'
    | '/admin/organization-tree'
    | '/admin/positions'
    | '/admin/regions'
    | '/admin/schools'
    | '/admin/source-channels'
    | '/admin/temp-disc-records'
    | '/admin/webhook-hooks'
    | '/admin/yunke-accounts'
    | '/crm/batch-import'
    | '/crm/continuous-call'
    | '/crm/lead-conversion'
    | '/crm/orders'
    | '/crm/workbench'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/admin'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/crm/leads/pool'
    | '/crm/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/login'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/admin/api-keys'
    | '/admin/areas'
    | '/admin/call-config'
    | '/admin/campus-departments'
    | '/admin/campuses'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/dingtalk-robots'
    | '/admin/disc-test'
    | '/admin/districts'
    | '/admin/employee-hierarchy'
    | '/admin/employees'
    | '/admin/identities'
    | '/admin/lead-access-stats'
    | '/admin/organization-tree'
    | '/admin/positions'
    | '/admin/regions'
    | '/admin/schools'
    | '/admin/source-channels'
    | '/admin/temp-disc-records'
    | '/admin/webhook-hooks'
    | '/admin/yunke-accounts'
    | '/crm/batch-import'
    | '/crm/continuous-call'
    | '/crm/lead-conversion'
    | '/crm/orders'
    | '/crm/workbench'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/admin'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/crm/leads/pool'
    | '/crm/leads'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/login'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/admin/api-keys'
    | '/_authenticated/admin/areas'
    | '/_authenticated/admin/call-config'
    | '/_authenticated/admin/campus-departments'
    | '/_authenticated/admin/campuses'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/departments'
    | '/_authenticated/admin/dingtalk-robots'
    | '/_authenticated/admin/disc-test'
    | '/_authenticated/admin/districts'
    | '/_authenticated/admin/employee-hierarchy'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/identities'
    | '/_authenticated/admin/lead-access-stats'
    | '/_authenticated/admin/organization-tree'
    | '/_authenticated/admin/positions'
    | '/_authenticated/admin/regions'
    | '/_authenticated/admin/schools'
    | '/_authenticated/admin/source-channels'
    | '/_authenticated/admin/temp-disc-records'
    | '/_authenticated/admin/webhook-hooks'
    | '/_authenticated/admin/yunke-accounts'
    | '/_authenticated/crm/batch-import'
    | '/_authenticated/crm/continuous-call'
    | '/_authenticated/crm/lead-conversion'
    | '/_authenticated/crm/orders'
    | '/_authenticated/crm/workbench'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/admin/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/crm/leads/pool'
    | '/_authenticated/crm/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/workbench': {
      id: '/_authenticated/crm/workbench'
      path: '/crm/workbench'
      fullPath: '/crm/workbench'
      preLoaderRoute: typeof AuthenticatedCrmWorkbenchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/orders': {
      id: '/_authenticated/crm/orders'
      path: '/crm/orders'
      fullPath: '/crm/orders'
      preLoaderRoute: typeof AuthenticatedCrmOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/lead-conversion': {
      id: '/_authenticated/crm/lead-conversion'
      path: '/crm/lead-conversion'
      fullPath: '/crm/lead-conversion'
      preLoaderRoute: typeof AuthenticatedCrmLeadConversionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/continuous-call': {
      id: '/_authenticated/crm/continuous-call'
      path: '/crm/continuous-call'
      fullPath: '/crm/continuous-call'
      preLoaderRoute: typeof AuthenticatedCrmContinuousCallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/batch-import': {
      id: '/_authenticated/crm/batch-import'
      path: '/crm/batch-import'
      fullPath: '/crm/batch-import'
      preLoaderRoute: typeof AuthenticatedCrmBatchImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/yunke-accounts': {
      id: '/_authenticated/admin/yunke-accounts'
      path: '/admin/yunke-accounts'
      fullPath: '/admin/yunke-accounts'
      preLoaderRoute: typeof AuthenticatedAdminYunkeAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/webhook-hooks': {
      id: '/_authenticated/admin/webhook-hooks'
      path: '/admin/webhook-hooks'
      fullPath: '/admin/webhook-hooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhookHooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/temp-disc-records': {
      id: '/_authenticated/admin/temp-disc-records'
      path: '/admin/temp-disc-records'
      fullPath: '/admin/temp-disc-records'
      preLoaderRoute: typeof AuthenticatedAdminTempDiscRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/source-channels': {
      id: '/_authenticated/admin/source-channels'
      path: '/admin/source-channels'
      fullPath: '/admin/source-channels'
      preLoaderRoute: typeof AuthenticatedAdminSourceChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/schools': {
      id: '/_authenticated/admin/schools'
      path: '/admin/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AuthenticatedAdminSchoolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/regions': {
      id: '/_authenticated/admin/regions'
      path: '/admin/regions'
      fullPath: '/admin/regions'
      preLoaderRoute: typeof AuthenticatedAdminRegionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/positions': {
      id: '/_authenticated/admin/positions'
      path: '/admin/positions'
      fullPath: '/admin/positions'
      preLoaderRoute: typeof AuthenticatedAdminPositionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/organization-tree': {
      id: '/_authenticated/admin/organization-tree'
      path: '/admin/organization-tree'
      fullPath: '/admin/organization-tree'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationTreeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/lead-access-stats': {
      id: '/_authenticated/admin/lead-access-stats'
      path: '/admin/lead-access-stats'
      fullPath: '/admin/lead-access-stats'
      preLoaderRoute: typeof AuthenticatedAdminLeadAccessStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/identities': {
      id: '/_authenticated/admin/identities'
      path: '/admin/identities'
      fullPath: '/admin/identities'
      preLoaderRoute: typeof AuthenticatedAdminIdentitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/employee-hierarchy': {
      id: '/_authenticated/admin/employee-hierarchy'
      path: '/admin/employee-hierarchy'
      fullPath: '/admin/employee-hierarchy'
      preLoaderRoute: typeof AuthenticatedAdminEmployeeHierarchyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/districts': {
      id: '/_authenticated/admin/districts'
      path: '/admin/districts'
      fullPath: '/admin/districts'
      preLoaderRoute: typeof AuthenticatedAdminDistrictsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/disc-test': {
      id: '/_authenticated/admin/disc-test'
      path: '/admin/disc-test'
      fullPath: '/admin/disc-test'
      preLoaderRoute: typeof AuthenticatedAdminDiscTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dingtalk-robots': {
      id: '/_authenticated/admin/dingtalk-robots'
      path: '/admin/dingtalk-robots'
      fullPath: '/admin/dingtalk-robots'
      preLoaderRoute: typeof AuthenticatedAdminDingtalkRobotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/departments': {
      id: '/_authenticated/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AuthenticatedAdminDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/campuses': {
      id: '/_authenticated/admin/campuses'
      path: '/admin/campuses'
      fullPath: '/admin/campuses'
      preLoaderRoute: typeof AuthenticatedAdminCampusesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/campus-departments': {
      id: '/_authenticated/admin/campus-departments'
      path: '/admin/campus-departments'
      fullPath: '/admin/campus-departments'
      preLoaderRoute: typeof AuthenticatedAdminCampusDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/call-config': {
      id: '/_authenticated/admin/call-config'
      path: '/admin/call-config'
      fullPath: '/admin/call-config'
      preLoaderRoute: typeof AuthenticatedAdminCallConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/areas': {
      id: '/_authenticated/admin/areas'
      path: '/admin/areas'
      fullPath: '/admin/areas'
      preLoaderRoute: typeof AuthenticatedAdminAreasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/admin/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/leads/': {
      id: '/_authenticated/crm/leads/'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AuthenticatedCrmLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/leads/pool': {
      id: '/_authenticated/crm/leads/pool'
      path: '/crm/leads/pool'
      fullPath: '/crm/leads/pool'
      preLoaderRoute: typeof AuthenticatedCrmLeadsPoolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
  AuthenticatedAdminAreasRoute: typeof AuthenticatedAdminAreasRoute
  AuthenticatedAdminCallConfigRoute: typeof AuthenticatedAdminCallConfigRoute
  AuthenticatedAdminCampusDepartmentsRoute: typeof AuthenticatedAdminCampusDepartmentsRoute
  AuthenticatedAdminCampusesRoute: typeof AuthenticatedAdminCampusesRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDepartmentsRoute: typeof AuthenticatedAdminDepartmentsRoute
  AuthenticatedAdminDingtalkRobotsRoute: typeof AuthenticatedAdminDingtalkRobotsRoute
  AuthenticatedAdminDiscTestRoute: typeof AuthenticatedAdminDiscTestRoute
  AuthenticatedAdminDistrictsRoute: typeof AuthenticatedAdminDistrictsRoute
  AuthenticatedAdminEmployeeHierarchyRoute: typeof AuthenticatedAdminEmployeeHierarchyRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminIdentitiesRoute: typeof AuthenticatedAdminIdentitiesRoute
  AuthenticatedAdminLeadAccessStatsRoute: typeof AuthenticatedAdminLeadAccessStatsRoute
  AuthenticatedAdminOrganizationTreeRoute: typeof AuthenticatedAdminOrganizationTreeRoute
  AuthenticatedAdminPositionsRoute: typeof AuthenticatedAdminPositionsRoute
  AuthenticatedAdminRegionsRoute: typeof AuthenticatedAdminRegionsRoute
  AuthenticatedAdminSchoolsRoute: typeof AuthenticatedAdminSchoolsRoute
  AuthenticatedAdminSourceChannelsRoute: typeof AuthenticatedAdminSourceChannelsRoute
  AuthenticatedAdminTempDiscRecordsRoute: typeof AuthenticatedAdminTempDiscRecordsRoute
  AuthenticatedAdminWebhookHooksRoute: typeof AuthenticatedAdminWebhookHooksRoute
  AuthenticatedAdminYunkeAccountsRoute: typeof AuthenticatedAdminYunkeAccountsRoute
  AuthenticatedCrmBatchImportRoute: typeof AuthenticatedCrmBatchImportRoute
  AuthenticatedCrmContinuousCallRoute: typeof AuthenticatedCrmContinuousCallRoute
  AuthenticatedCrmLeadConversionRoute: typeof AuthenticatedCrmLeadConversionRoute
  AuthenticatedCrmOrdersRoute: typeof AuthenticatedCrmOrdersRoute
  AuthenticatedCrmWorkbenchRoute: typeof AuthenticatedCrmWorkbenchRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedCrmLeadsPoolRoute: typeof AuthenticatedCrmLeadsPoolRoute
  AuthenticatedCrmLeadsIndexRoute: typeof AuthenticatedCrmLeadsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
  AuthenticatedAdminAreasRoute: AuthenticatedAdminAreasRoute,
  AuthenticatedAdminCallConfigRoute: AuthenticatedAdminCallConfigRoute,
  AuthenticatedAdminCampusDepartmentsRoute:
    AuthenticatedAdminCampusDepartmentsRoute,
  AuthenticatedAdminCampusesRoute: AuthenticatedAdminCampusesRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDepartmentsRoute: AuthenticatedAdminDepartmentsRoute,
  AuthenticatedAdminDingtalkRobotsRoute: AuthenticatedAdminDingtalkRobotsRoute,
  AuthenticatedAdminDiscTestRoute: AuthenticatedAdminDiscTestRoute,
  AuthenticatedAdminDistrictsRoute: AuthenticatedAdminDistrictsRoute,
  AuthenticatedAdminEmployeeHierarchyRoute:
    AuthenticatedAdminEmployeeHierarchyRoute,
  AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
  AuthenticatedAdminIdentitiesRoute: AuthenticatedAdminIdentitiesRoute,
  AuthenticatedAdminLeadAccessStatsRoute:
    AuthenticatedAdminLeadAccessStatsRoute,
  AuthenticatedAdminOrganizationTreeRoute:
    AuthenticatedAdminOrganizationTreeRoute,
  AuthenticatedAdminPositionsRoute: AuthenticatedAdminPositionsRoute,
  AuthenticatedAdminRegionsRoute: AuthenticatedAdminRegionsRoute,
  AuthenticatedAdminSchoolsRoute: AuthenticatedAdminSchoolsRoute,
  AuthenticatedAdminSourceChannelsRoute: AuthenticatedAdminSourceChannelsRoute,
  AuthenticatedAdminTempDiscRecordsRoute:
    AuthenticatedAdminTempDiscRecordsRoute,
  AuthenticatedAdminWebhookHooksRoute: AuthenticatedAdminWebhookHooksRoute,
  AuthenticatedAdminYunkeAccountsRoute: AuthenticatedAdminYunkeAccountsRoute,
  AuthenticatedCrmBatchImportRoute: AuthenticatedCrmBatchImportRoute,
  AuthenticatedCrmContinuousCallRoute: AuthenticatedCrmContinuousCallRoute,
  AuthenticatedCrmLeadConversionRoute: AuthenticatedCrmLeadConversionRoute,
  AuthenticatedCrmOrdersRoute: AuthenticatedCrmOrdersRoute,
  AuthenticatedCrmWorkbenchRoute: AuthenticatedCrmWorkbenchRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedCrmLeadsPoolRoute: AuthenticatedCrmLeadsPoolRoute,
  AuthenticatedCrmLeadsIndexRoute: AuthenticatedCrmLeadsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
